[package]
name = "highscore"
version = "1.0.0"
edition = "2018"

[dependencies]
casper-contract = "1.4.4"
casper-types = "1.5.0"

[[bin]]
name = "highscore"
path = "src/main.rs"
bench = false
doctest = false
test = false 

[profile.release]
codegen-units = 1
lto = true
